export const seedBrands = [
  {
    name: 'Samsung',
    slug: 'samsung',
    logo: 'samsung-logo.svg',
    is_featured: true,
  },
  {
    name: 'Apple',
    slug: 'apple',
    logo: 'apple-logo.svg',
    is_featured: true,
  },
  {
    name: 'Sony',
    slug: 'sony',
    logo: 'sony-logo.svg',
    is_featured: true,
  },
  {
    name: 'Microsoft',
    slug: 'microsoft',
    logo: 'microsoft-logo.svg',
    is_featured: true,
  },
  {
    name: 'HP',
    slug: 'hp',
    logo: 'hp-logo.svg',
    is_featured: true,
  },
  {
    name: 'Dell',
    slug: 'dell',
    logo: 'dell-logo.svg',
    is_featured: true,
  },
  {
    name: 'Lenovo',
    slug: 'lenovo',
    logo: 'lenovo-logo.svg',
    is_featured: true,
  },
  {
    name: 'Asus',
    slug: 'asus',
    logo: 'asus-logo.svg',
    is_featured: false,
  },
  {
    name: 'Acer',
    slug: 'acer',
    logo: 'acer-logo.svg',
    is_featured: false,
  },
  {
    name: 'Xiaomi',
    slug: 'xiaomi',
    logo: 'xiaomi-logo.svg',
    is_featured: true,
  },
  {
    name: 'Huawei',
    slug: 'huawei',
    logo: 'huawei-logo.svg',
    is_featured: false,
  },
  {
    name: 'Google',
    slug: 'google',
    logo: 'google-logo.svg',
    is_featured: true,
  },
  {
    name: 'Nike',
    slug: 'nike',
    logo: 'nike-logo.svg',
    is_featured: true,
  },
  {
    name: 'Adidas',
    slug: 'adidas',
    logo: 'adidas-logo.svg',
    is_featured: true,
  },
  {
    name: 'Puma',
    slug: 'puma',
    logo: 'puma-logo.svg',
    is_featured: false,
  },
  {
    name: 'Reebok',
    slug: 'reebok',
    logo: 'reebok-logo.svg',
    is_featured: false,
  },
  {
    name: 'Zara',
    slug: 'zara',
    logo: 'zara-logo.svg',
    is_featured: true,
  },
  {
    name: 'H&M',
    slug: 'hm',
    logo: 'hm-logo.svg',
    is_featured: true,
  },
  {
    name: 'Levis',
    slug: 'levis',
    logo: 'levis-logo.svg',
    is_featured: false,
  },
  {
    name: 'Canon',
    slug: 'canon',
    logo: 'canon-logo.svg',
    is_featured: true,
  },
  {
    name: 'Nikon',
    slug: 'nikon',
    logo: 'nikon-logo.svg',
    is_featured: false,
  },
  {
    name: 'Philips',
    slug: 'philips',
    logo: 'philips-logo.svg',
    is_featured: false,
  },
  {
    name: 'LG',
    slug: 'lg',
    logo: 'lg-logo.svg',
    is_featured: true,
  },
  {
    name: 'Bose',
    slug: 'bose',
    logo: 'bose-logo.svg',
    is_featured: true,
  },
  {
    name: 'JBL',
    slug: 'jbl',
    logo: 'jbl-logo.svg',
    is_featured: false,
  },
];