export const seedProducts = [
  // Electronics - Smartphones
  {
    name: 'Galaxy S22 Ultra',
    slug: 'galaxy-s22-ultra',
    description: 'The Samsung Galaxy S22 Ultra features a 6.8-inch Dynamic AMOLED display, a powerful Exynos processor, a versatile quad-camera system, and the S Pen stylus. Experience exceptional performance and premium design.',
    price: 1199.99,
    sale_price: 1099.99,
    sku: 'SAMS22U-01',
    stock: 150,
    is_featured: true,
    is_published: true,
    images: [
      'galaxy-s22-ultra-1.jpg',
      'galaxy-s22-ultra-2.jpg',
      'galaxy-s22-ultra-3.jpg',
    ],
  },
  {
    name: 'iPhone 14 Pro',
    slug: 'iphone-14-pro',
    description: 'The iPhone 14 Pro introduces the Dynamic Island, a new way to interact with your iPhone. Featuring the A16 Bionic chip, a 48MP main camera, and a Super Retina XDR display with Always-On, it delivers unparalleled performance.',
    price: 1099.99,
    sale_price: null,
    sku: 'IPH14P-01',
    stock: 100,
    is_featured: true,
    is_published: true,
    images: [
      'iphone-14-pro-1.jpg',
      'iphone-14-pro-2.jpg',
      'iphone-14-pro-3.jpg',
    ],
  },
  
  // Electronics - Laptops
  {
    name: 'MacBook Pro 16" M2',
    slug: 'macbook-pro-16-m2',
    description: 'The MacBook Pro 16" with M2 Pro chip delivers extraordinary performance and battery life. Featuring a stunning Liquid Retina XDR display, numerous ports for advanced connectivity, and a 1080p camera, it is designed for professionals.',
    price: 2499.99,
    sale_price: 2299.99,
    sku: 'MBPM2-16',
    stock: 50,
    is_featured: true,
    is_published: true,
    images: [
      'macbook-pro-m2-1.jpg',
      'macbook-pro-m2-2.jpg',
      'macbook-pro-m2-3.jpg',
    ],
  },
  {
    name: 'Dell XPS 15',
    slug: 'dell-xps-15',
    description: 'The Dell XPS 15 combines powerful performance with a stunning 4K UHD+ display. Powered by the latest Intel processors and NVIDIA graphics, it offers a premium experience for creators and professionals.',
    price: 1899.99,
    sale_price: 1799.99,
    sku: 'DELXPS15-01',
    stock: 75,
    is_featured: true,
    is_published: true,
    images: [
      'dell-xps-15-1.jpg',
      'dell-xps-15-2.jpg',
      'dell-xps-15-3.jpg',
    ],
  },
  
  // Electronics - Audio Devices
  {
    name: 'Sony WH-1000XM5',
    slug: 'sony-wh-1000xm5',
    description: 'The Sony WH-1000XM5 headphones redefine noise cancelling with two processors and eight microphones. Enjoy industry-leading sound quality, crystal clear calls, and up to 30 hours of battery life.',
    price: 399.99,
    sale_price: 349.99,
    sku: 'SNYM5-01',
    stock: 200,
    is_featured: true,
    is_published: true,
    images: [
      'sony-wh-1000xm5-1.jpg',
      'sony-wh-1000xm5-2.jpg',
      'sony-wh-1000xm5-3.jpg',
    ],
  },
  {
    name: 'Bose QuietComfort Earbuds II',
    slug: 'bose-quietcomfort-earbuds-ii',
    description: 'The Bose QuietComfort Earbuds II offer personalized noise cancellation and sound. These wireless earbuds feature proprietary CustomTune technology that automatically adjusts to your ears for immersive audio experience.',
    price: 299.99,
    sale_price: null,
    sku: 'BOSQCE2-01',
    stock: 150,
    is_featured: false,
    is_published: true,
    images: [
      'bose-quietcomfort-earbuds-ii-1.jpg',
      'bose-quietcomfort-earbuds-ii-2.jpg',
      'bose-quietcomfort-earbuds-ii-3.jpg',
    ],
  },
  
  // Fashion - Men's Clothing
  {
    name: 'Classic Fit Cotton Shirt',
    slug: 'classic-fit-cotton-shirt',
    description: 'This classic-fit cotton shirt is perfect for any occasion. Made from 100% premium cotton, it offers comfort, durability, and timeless style. Available in multiple colors and sizes.',
    price: 49.99,
    sale_price: 39.99,
    sku: 'MCFS-01',
    stock: 300,
    is_featured: true,
    is_published: true,
    images: [
      'classic-fit-cotton-shirt-1.jpg',
      'classic-fit-cotton-shirt-2.jpg',
      'classic-fit-cotton-shirt-3.jpg',
    ],
  },
  {
    name: 'Slim Fit Stretch Jeans',
    slug: 'slim-fit-stretch-jeans',
    description: 'These slim-fit stretch jeans combine style and comfort. The premium denim with added stretch provides flexibility while maintaining a sleek silhouette. Perfect for everyday wear.',
    price: 79.99,
    sale_price: 59.99,
    sku: 'MSFJ-01',
    stock: 250,
    is_featured: false,
    is_published: true,
    images: [
      'slim-fit-stretch-jeans-1.jpg',
      'slim-fit-stretch-jeans-2.jpg',
      'slim-fit-stretch-jeans-3.jpg',
    ],
  },
  
  // Fashion - Women's Clothing
  {
    name: 'Floral Print Summer Dress',
    slug: 'floral-print-summer-dress',
    description: 'This beautiful floral print summer dress is perfect for warm days. Made from lightweight, breathable fabric, it features an elegant design with a flattering silhouette and comfortable fit.',
    price: 69.99,
    sale_price: 49.99,
    sku: 'WFPSD-01',
    stock: 200,
    is_featured: true,
    is_published: true,
    images: [
      'floral-print-summer-dress-1.jpg',
      'floral-print-summer-dress-2.jpg',
      'floral-print-summer-dress-3.jpg',
    ],
  },
  {
    name: 'High-Waisted Tailored Pants',
    slug: 'high-waisted-tailored-pants',
    description: 'These sophisticated high-waisted tailored pants are a versatile addition to any wardrobe. Made from premium fabric with a comfortable stretch, they offer both elegance and functionality.',
    price: 89.99,
    sale_price: null,
    sku: 'WHWTP-01',
    stock: 175,
    is_featured: false,
    is_published: true,
    images: [
      'high-waisted-tailored-pants-1.jpg',
      'high-waisted-tailored-pants-2.jpg',
      'high-waisted-tailored-pants-3.jpg',
    ],
  },
  
  // Home & Garden - Furniture
  {
    name: 'Modern Sectional Sofa',
    slug: 'modern-sectional-sofa',
    description: 'This modern sectional sofa combines style, comfort, and functionality. Featuring premium upholstery, sturdy construction, and a modular design, it is perfect for any living space.',
    price: 1299.99,
    sale_price: 999.99,
    sku: 'HMSS-01',
    stock: 30,
    is_featured: true,
    is_published: true,
    images: [
      'modern-sectional-sofa-1.jpg',
      'modern-sectional-sofa-2.jpg',
      'modern-sectional-sofa-3.jpg',
    ],
  },
  {
    name: 'Queen Size Platform Bed',
    slug: 'queen-size-platform-bed',
    description: 'This queen-size platform bed features a sleek, minimalist design with solid wood construction. The sturdy platform eliminates the need for a box spring, while providing excellent support for your mattress.',
    price: 699.99,
    sale_price: 599.99,
    sku: 'HQSPB-01',
    stock: 25,
    is_featured: false,
    is_published: true,
    images: [
      'queen-size-platform-bed-1.jpg',
      'queen-size-platform-bed-2.jpg',
      'queen-size-platform-bed-3.jpg',
    ],
  },
  
  // Beauty & Health - Skincare
  {
    name: 'Advanced Anti-Aging Face Cream',
    slug: 'advanced-anti-aging-face-cream',
    description: 'This advanced anti-aging face cream is formulated with powerful ingredients to reduce the appearance of fine lines and wrinkles. It hydrates and nourishes your skin, promoting a youthful, radiant complexion.',
    price: 79.99,
    sale_price: 69.99,
    sku: 'BSAAFC-01',
    stock: 120,
    is_featured: true,
    is_published: true,
    images: [
      'advanced-anti-aging-face-cream-1.jpg',
      'advanced-anti-aging-face-cream-2.jpg',
      'advanced-anti-aging-face-cream-3.jpg',
    ],
  },
  {
    name: 'Vitamin C Brightening Serum',
    slug: 'vitamin-c-brightening-serum',
    description: 'This potent Vitamin C serum brightens and evens skin tone while reducing the appearance of dark spots. Formulated with powerful antioxidants, it protects against environmental damage for radiant, healthy-looking skin.',
    price: 59.99,
    sale_price: null,
    sku: 'BSVCBS-01',
    stock: 150,
    is_featured: false,
    is_published: true,
    images: [
      'vitamin-c-brightening-serum-1.jpg',
      'vitamin-c-brightening-serum-2.jpg',
      'vitamin-c-brightening-serum-3.jpg',
    ],
  },
  
  // Sports & Outdoors - Exercise Equipment
  {
    name: 'Premium Adjustable Dumbbell Set',
    slug: 'premium-adjustable-dumbbell-set',
    description: 'This premium adjustable dumbbell set offers versatility and convenience for home workouts. Quickly switch between weights with an innovative adjustment mechanism, saving space while providing a complete strength training solution.',
    price: 349.99,
    sale_price: 299.99,
    sku: 'SEPADS-01',
    stock: 50,
    is_featured: true,
    is_published: true,
    images: [
      'premium-adjustable-dumbbell-set-1.jpg',
      'premium-adjustable-dumbbell-set-2.jpg',
      'premium-adjustable-dumbbell-set-3.jpg',
    ],
  },
  {
    name: 'Foldable Exercise Bike',
    slug: 'foldable-exercise-bike',
    description: 'This foldable exercise bike combines convenience with effective cardio training. Featuring multiple resistance levels, an LCD display for tracking progress, and a comfortable seat, it is perfect for home workouts and easily stores away when not in use.',
    price: 249.99,
    sale_price: 199.99,
    sku: 'SEFEB-01',
    stock: 75,
    is_featured: false,
    is_published: true,
    images: [
      'foldable-exercise-bike-1.jpg',
      'foldable-exercise-bike-2.jpg',
      'foldable-exercise-bike-3.jpg',
    ],
  },
  
  // Toys & Kids - Toys
  {
    name: 'Educational Building Blocks Set',
    slug: 'educational-building-blocks-set',
    description: 'This educational building blocks set helps develop creativity, fine motor skills, and spatial awareness. Made from high-quality, child-safe materials, it includes various shapes and colors for endless construction possibilities.',
    price: 39.99,
    sale_price: 34.99,
    sku: 'KTEBBS-01',
    stock: 100,
    is_featured: true,
    is_published: true,
    images: [
      'educational-building-blocks-set-1.jpg',
      'educational-building-blocks-set-2.jpg',
      'educational-building-blocks-set-3.jpg',
    ],
  },
  {
    name: 'Remote Control Car',
    slug: 'remote-control-car',
    description: 'This high-speed remote control car provides hours of entertainment. With durable construction, responsive controls, and long battery life, it is suitable for both indoor and outdoor play.',
    price: 69.99,
    sale_price: 59.99,
    sku: 'KTRCC-01',
    stock: 80,
    is_featured: false,
    is_published: true,
    images: [
      'remote-control-car-1.jpg',
      'remote-control-car-2.jpg',
      'remote-control-car-3.jpg',
    ],
  },
];