export const seedShops = [
  {
    name: 'Tech Haven',
    description: 'Your one-stop shop for all things technology. We offer the latest smartphones, laptops, and electronics with expert advice and competitive prices.',
    logo: 'tech-haven-logo.png',
    banner: 'tech-haven-banner.jpg',
    is_verified: true,
    is_featured: true,
  },
  {
    name: 'Fashion Forward',
    description: 'Trendy and affordable fashion for all. We curate the latest styles in clothing, footwear, and accessories for men and women.',
    logo: 'fashion-forward-logo.png',
    banner: 'fashion-forward-banner.jpg',
    is_verified: true,
    is_featured: true,
  },
  {
    name: 'Home Essentials',
    description: 'Transform your living space with our wide range of home decor, furniture, and kitchen essentials. Quality products for every room in your home.',
    logo: 'home-essentials-logo.png',
    banner: 'home-essentials-banner.jpg',
    is_verified: true,
    is_featured: true,
  },
  {
    name: 'Beauty Box',
    description: 'Premium beauty products for skincare, makeup, and haircare. We bring you the best brands and beauty solutions for all your needs.',
    logo: 'beauty-box-logo.png',
    banner: 'beauty-box-banner.jpg',
    is_verified: true,
    is_featured: false,
  },
  {
    name: 'Sports World',
    description: 'Everything for the sports enthusiast. From exercise equipment to outdoor gear and sports apparel, we have your active lifestyle covered.',
    logo: 'sports-world-logo.png',
    banner: 'sports-world-banner.jpg',
    is_verified: true,
    is_featured: false,
  },
  {
    name: 'Kids Corner',
    description: 'A paradise for children and parents. Find toys, kids clothing, and baby products that are safe, fun, and educational.',
    logo: 'kids-corner-logo.png',
    banner: 'kids-corner-banner.jpg',
    is_verified: true,
    is_featured: false,
  },
  {
    name: 'Book Nook',
    description: 'For the love of reading. Discover a vast collection of books across all genres, from bestsellers to classics and everything in between.',
    logo: 'book-nook-logo.png',
    banner: 'book-nook-banner.jpg',
    is_verified: true,
    is_featured: false,
  },
  {
    name: 'Auto Zone',
    description: 'Keep your vehicle at its best. We offer car accessories, motorcycle gear, and auto care products for all your automotive needs.',
    logo: 'auto-zone-logo.png',
    banner: 'auto-zone-banner.jpg',
    is_verified: true,
    is_featured: false,
  },
  {
    name: 'Gadget Hub',
    description: 'Explore the world of innovative gadgets. From smart home devices to the latest tech accessories, we bring innovation to your fingertips.',
    logo: 'gadget-hub-logo.png',
    banner: 'gadget-hub-banner.jpg',
    is_verified: false,
    is_featured: false,
  },
  {
    name: 'Fitness First',
    description: 'Achieve your fitness goals with our premium exercise equipment, supplements, and workout accessories. Your health journey starts here.',
    logo: 'fitness-first-logo.png',
    banner: 'fitness-first-banner.jpg',
    is_verified: false,
    is_featured: false,
  },
];